server:
    port: 8080

app:
    eureka-server: localhost

spring:
    application:
        name: api-gateway
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            probability: 1.0

    cloud:
        gateway:
            routes:
            -   id: product-service
                uri: lb://product-service
                predicates:
                - Path=/api/product
            -   id: order-service
                uri: lb://order-service
                predicates:
                - Path=/api/order
            -   id: discovery-server
                uri: http://eureka:password@${app.eureka-server}:8761
                predicates:
                - Path=/eureka/web
                filters:
                - SetPath=/
            -   id: discovery-server-static
                uri: http://eureka:password@${app.eureka-server}:8761
                predicates:
                - Path=/eureka/**

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
                    gateway.route.RouteDefinitionRouteLocator: INFO
        root: INFO
