server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: password
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0